# -*- coding: utf-8 -*-
"""Códigos_PEXV_

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGQW6ONKeuwSyb9YUblxbnQu5FyCu07L
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

start_date = datetime(2025, 1, 1)
num_entries = 150
date_range = [start_date + timedelta(days=np.random.randint(0, 90)) for _ in range(num_entries)]
income_categories = {'Papelaria': 0.4, 'Armarinho': 0.3, 'Serviços (Recarga/Impressão)': 0.3}
expense_categories = {
    'Estoque/Reposição': 0.5, 'Salários/Comissões': 0.2,
    'Aluguel/IPTU': 0.1, 'Utilidades (Luz/Água/Internet)': 0.1,
    'Manutenção/Outros': 0.1
}

data_transacoes = []
for date in date_range:
    entry_type = np.random.choice(['income', 'expense'], p=[0.6, 0.4])

    if entry_type == 'income':
        category = np.random.choice(list(income_categories.keys()), p=list(income_categories.values()))
        value = np.random.uniform(10, 150) if category == 'Papelaria' else (
                np.random.uniform(5, 80) if category == 'Armarinho' else np.random.uniform(5, 50))
        description = f"Venda de {category.lower()}"
    else:
        category = np.random.choice(list(expense_categories.keys()), p=list(expense_categories.values()))
        value = np.random.uniform(100, 800)
        if category in ['Salários/Comissões']:
            value = np.random.uniform(3000, 4000)
        elif category in ['Aluguel/IPTU']:
             value = np.random.uniform(1500, 2000)
        if category in ['Salários/Comissões', 'Aluguel/IPTU']:
            value = round(value / 100) * 100

        description = f"Pagamento de {category.lower()}"

    data_transacoes.append({
        'Data': date.strftime('%Y-%m-%d'), 'Tipo': entry_type, 'Categoria': category,
        'Descrição': description, 'Valor': round(value, 2)
    })

df_transacoes = pd.DataFrame(data_transacoes).sort_values(by='Data').reset_index(drop=True)
df_transacoes.to_csv('dados_armarinho_ficticios.csv', index=False)

orcamento_base = {
    'Estoque/Reposição': 11000.00, 'Salários/Comissões': 3200.00,
    'Aluguel/IPTU': 1600.00, 'Utilidades (Luz/Água/Internet)': 350.00,
    'Manutenção/Outros': 600.00
}
meses = ['2025-01', '2025-02', '2025-03']
orcamento_data = []

for mes_str in meses:
    for categoria, valor_base in orcamento_base.items():
        valor_orcado = valor_base * (1 + random.uniform(-0.05, 0.05))
        orcamento_data.append({'Mes_Ano': mes_str, 'Categoria': categoria, 'Orçamento_Previsto': round(valor_orcado, 2)})

df_orcamento = pd.DataFrame(orcamento_data)
df_orcamento.to_csv('orcamento_mensal_ficticio.csv', index=False)

contas_recorrentes = [
    {'Categoria': 'Aluguel/IPTU', 'Descricao': 'Aluguel do Ponto Comercial', 'Valor_Fixo': 1800.00, 'Dia_Vencimento': 5},
    {'Categoria': 'Salários/Comissões', 'Descricao': 'Salário Fixo do Administrador/Caixa', 'Valor_Fixo': 3200.00, 'Dia_Vencimento': 30},
    {'Categoria': 'Utilidades (Luz/Água/Internet)', 'Descricao': 'Internet/Telefone Fixo', 'Valor_Fixo': 150.00, 'Dia_Vencimento': 15},
    {'Categoria': 'Manutenção/Outros', 'Descricao': 'Serviço de Contabilidade', 'Valor_Fixo': 250.00, 'Dia_Vencimento': 10}
]

df_fixas = pd.DataFrame(contas_recorrentes)
df_fixas.to_csv('contas_fixas_ficticias.csv', index=False)

print("✅ Três arquivos CSV criados na sua sessão Colab.")

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 7)

df_real = pd.read_csv('dados_armarinho_ficticios.csv')
df_real['Data'] = pd.to_datetime(df_real['Data'])
df_real['Mes_Ano'] = df_real['Data'].dt.to_period('M').astype(str)

df_orcamento = pd.read_csv('orcamento_mensal_ficticio.csv')
df_fixas = pd.read_csv('contas_fixas_ficticias.csv')

print("✅ Todos os DataFrames carregados e prontos para análise.")

df_despesas = df_real[df_real['Tipo'] == 'expense']
gastos_por_categoria = df_despesas.groupby('Categoria')['Valor'].sum().sort_values(ascending=False)

plt.figure(figsize=(12, 7))
sns.barplot(
    x=gastos_por_categoria.index,
    y=gastos_por_categoria.values,
    hue=gastos_por_categoria.index,
    palette="rocket",
    legend=False
)
plt.title('Distribuição Total das Despesas por Categoria', fontsize=16)
plt.xlabel('Categoria de Despesa')
plt.ylabel('Valor Total (R$)')
plt.xticks(rotation=45, ha='right')
plt.show()

fluxo_mensal = df_real.pivot_table(
    index='Mes_Ano', columns='Tipo', values='Valor', aggfunc='sum', fill_value=0
).reset_index()
fluxo_mensal['Lucro_Liquido'] = fluxo_mensal['income'] - fluxo_mensal['expense']
fluxo_mensal['Mes_Ano'] = fluxo_mensal['Mes_Ano'].astype(str)

fig, ax1 = plt.subplots()
largura_barra = 0.35
posicoes = np.arange(len(fluxo_mensal['Mes_Ano']))

ax1.bar(posicoes - largura_barra/2, fluxo_mensal['expense'], largura_barra, label='Despesa', color='tomato')
ax1.bar(posicoes + largura_barra/2, fluxo_mensal['income'], largura_barra, label='Receita', color='mediumseagreen')
ax1.set_ylabel('Valor (R$)', color='black')

ax2 = ax1.twinx()
ax2.plot(posicoes, fluxo_mensal['Lucro_Liquido'], marker='o', linestyle='--', color='darkblue', label='Lucro Líquido', linewidth=2)
ax2.axhline(0, color='gray', linestyle='-')

ax2.set_ylabel('Lucro Líquido (R$)', color='darkblue')
plt.title('Fluxo de Caixa Mensal: Receita, Despesa e Lucro Líquido', fontsize=16)
ax1.set_xticks(posicoes)
ax1.set_xticklabels(fluxo_mensal['Mes_Ano'])
fig.legend(loc="upper left", bbox_to_anchor=(0.15, 0.9))
plt.tight_layout()
plt.show()

gasto_real_agregado = df_real.groupby(['Mes_Ano', 'Categoria'])['Valor'].sum().reset_index()
gasto_real_agregado.rename(columns={'Valor': 'Gasto_Real'}, inplace=True)

df_comparacao = pd.merge(
    df_orcamento,
    gasto_real_agregado,
    on=['Mes_Ano', 'Categoria'],
    how='left'
).fillna(0)
df_comparacao['Diferenca'] = df_comparacao['Gasto_Real'] - df_comparacao['Orçamento_Previsto']

df_mensal_total = df_comparacao.groupby('Mes_Ano')[['Orçamento_Previsto', 'Gasto_Real']].sum().reset_index()

plt.figure(figsize=(12, 7))

posicoes = np.arange(len(df_mensal_total['Mes_Ano']))
largura_barra = 0.35

plt.bar(posicoes - largura_barra/2, df_mensal_total['Orçamento_Previsto'], largura_barra, label='Orçamento Previsto', color='steelblue')
plt.bar(posicoes + largura_barra/2, df_mensal_total['Gasto_Real'], largura_barra, label='Gasto Real', color='coral')

plt.title('Desempenho Mensal: Gasto Real vs. Orçamento Previsto', fontsize=16)
plt.xlabel('Mês')
plt.ylabel('Valor Total (R$)')
plt.xticks(posicoes, df_mensal_total['Mes_Ano'])
plt.legend()
plt.grid(axis='y')
plt.tight_layout()
plt.show()